# BDIViz User Test Case 2

## Supplimentary Material

---
  
#### Paper info: 

_Dou et al._

  
We characterized a prospective endometrial carcinoma (EC) cohort containing 138 tumors and 20 enriched normal tissues using 10 different omics platforms. Targeted quantitation of two peptides can predict antigen processing and presentation machinery activity, and may inform patient selection for immunotherapy. Association analysis between MYC activity and metformin treatment in both patients and cell lines suggests a potential role for metformin treatment in non-diabetic patients with elevated MYC activity. PIK3R1 in-frame indels are associated with elevated AKT phosphorylation and increased sensitivity to AKT inhibitors. CTNNB1 hotspot mutations are concentrated near phosphorylation sites mediating pS45-induced degradation of β-catenin, which may render Wnt-FZD antagonists ineffective. Deep learning accurately predicts EC subtypes and mutations from histopathology images, which may be useful for rapid diagnosis. Overall, this study identified molecular and imaging markers that can be further investigated to guide patient stratification for more precise treatment of EC.  

- [**Dou, et al: CPTAC Discovery**](https://pubmed.ncbi.nlm.nih.gov/32059776/)  

- [**Dou, et al: CPTAC Confirmatory**](https://pubmed.ncbi.nlm.nih.gov/37567170/)

## 0. Load Dataset

In [1]:
import pandas as pd
import numpy as np

import panel as pn

In [2]:
# Dou sample #1
source = pd.read_csv("Dou-ucec-sample-1.csv").drop(columns=["Unnamed: 0"])

target = pd.read_csv("Dou-ucec-confirmatory.csv")

In [3]:
source

,BMI,Ethnicity,Proteomics_Tumor_Normal,Estrogen_Receptor,PMS2,CIBERSORT_Mast _cells _activated,Genomics_subtype,ESTIMATE_StromalScore,Clin_Stage_Dist_Mets-cM,Path_Stage_Dist_Mets-pM
0,38.88,Not-Hispanic or Latino,Tumor,Cannot be determined,Intact nuclear expression,0.000000,MSI-H,2821.088429,cM0,Staging Incomplete
1,39.76,Not-Hispanic or Latino,Tumor,Cannot be determined,Loss of nuclear expression,0.015087,MSI-H,2714.248104,cM0,Staging Incomplete
2,51.19,Not-Hispanic or Latino,Tumor,Cannot be determined,Intact nuclear expression,0.033825,CNV_low,3856.501277,cM0,Staging Incomplete
3,NaN,NaN,Tumor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32.69,Not-Hispanic or Latino,Tumor,Cannot be determined,Intact nuclear expression,0.000000,CNV_low,3012.556593,cM0,No pathologic evidence of distant metastasis
...,...,...,...,...,...,...,...,...,...,...
148,NaN,NaN,Enriched_normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,NaN,NaN,Enriched_normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,NaN,NaN,Enriched_normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,NaN,NaN,Enriched_normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,NaN,NaN,Enriched_normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
target

,Unnamed: 0,Idx,Case_id,Case_excluded,Batch,Plex,ReporterName,Aliquot_ID,Group,Discovery_study,...,Follow-up_additional_surgery_for_new_tumor,Follow-up_additional_treatment_radiation_therapy_for_new_tumor,Follow-up_additional_treatment_pharmaceutical_therapy_for_new_tumor,Follow-up_additional_treatment_immuno_for_new_tumor,Follow-up_days_from_date_of_collection_to_date_of_last_contact,Follow-up_cause_of_death,Follow-up_days_from_date_of_initial_pathologic_diagnosis_to_date_of_death,Follow-up_days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor,Follow-up_procedure_type_of_new_tumor,Follow-up_residual_tumor_after_surgery_for_new_tumor
0,0,C3L-00086,C3L-00086,No,b4,16.0,128N,CPT0092460003,Tumor,No,...,n/a|No|No|No|No,n/a|Yes|Yes|Yes|Yes,n/a|Yes|Yes|Yes|Yes,n/a|No|No|No|No,330.0|701.0|1046.0|1436.0|n/a,n/a|n/a|n/a|n/a|Breast Carcinoma,n/a|n/a|n/a|n/a|1578.0,n/a|n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a|n/a
1,1,C3L-00898,C3L-00898,No,b4,14.0,128C,CPT0172200008,Tumor,No,...,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,396.0|746.0|982.0|1600.0,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a
2,2,C3L-00943,C3L-00943,No,b4,15.0,130C,CPT0086090003,Tumor,No,...,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a,237.0|693.0|1039.0,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a
3,3,C3L-01064,C3L-01064,No,b3,9.0,129N,CPT0113430004,Tumor,No,...,No|No|No|No,No|Yes|No|No,Yes|Yes|Yes|Yes,No|No|No|No,453.0|726.0|1062.0|1447.0,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a,n/a|n/a|n/a|n/a
4,4,C3L-01277,C3L-01277,No,b4,13.0,130N,CPT0093170003,Tumor,No,...,n/a|No|No,n/a|No|Yes,n/a|Yes|No,n/a|No|No,351.0|713.0|967.0,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a,n/a|n/a|n/a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,185,NX034,NX034,No,b1,4.0,129N,CPT0313400002,Enriched_Normal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,186,NX035,NX035,No,b1,3.0,129C,CPT0313420003,Enriched_Normal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,187,NX036,NX036,No,b2,7.0,129N,CPT0313490002,Enriched_Normal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,188,NX037,NX037,No,b4,16.0,130C,CPT0313420007,Enriched_Normal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,189,NX038,NX038,No,b2,6.0,131C,CPT0313420004,Enriched_Normal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN