## Exploring Matching Candidates with BDI-Viz

**GDC Metadata Validation Services:**
https://docs.gdc.cancer.gov/Data_Dictionary/gdcmvs/ 
  
**Data Dictionary Viewer:**
https://docs.gdc.cancer.gov/Data_Dictionary/viewer/


---
  
#### Paper info: [link](https://www.sciencedirect.com/science/article/pii/S0092867420301070)

_**Proteogenomic Characterization of Endometrial Carcinoma**_  

_Dou et. al_

We undertook a comprehensive proteogenomic characterization of 95 prospectively collected endometrial carcinomas, comprising 83 endometrioid and 12 serous tumors. This analysis revealed possible new consequences of perturbations to the p53 and Wnt/β-catenin pathways, identified a potential role for circRNAs in the epithelial-mesenchymal transition, and provided new information about proteomic markers of clinical and genomic tumor subgroups, including relationships to known druggable pathways. An extensive genome-wide acetylation survey yielded insights into regulatory mechanisms linking Wnt signaling and histone acetylation. We also characterized aspects of the tumor immune landscape, including immunogenic alterations, neoantigens, common cancer/testis antigens, and the immune microenvironment, all of which can inform immunotherapy decisions. Collectively, our multi-omic analyses provide a valuable resource for researchers and clinicians, identify new molecular associations of potential mechanistic significance in the development of endometrial cancers, and suggest novel approaches for identifying potential therapeutic targets.



#### Scenario:
The Clinical Proteomic Tumor Analysis Consortium (CPTAC) program wants to make the data from its multiple studies readily available in an integrated, standardized format in the Cancer Research  Data Commons (CRDC). Much of the patient case and sample data are available in supplemental tables in the original primary research papers, but with varying variable names and value types. This exercise is based on the study by Dou et al, Proteogenomic data and resources for pan-cancer analysis: Cancer Cell, which integrated and harmonized data from ten CPTAC source studies. 

#### Task:
Semi-automatically extract and integrate patient case metadata from the ten source studies. Create a harmonized dataset in the Genomics Data Commons (GDC) data format. Include only patients that have tumor samples with proteogenomic data and were not excluded in the source studies.

In [1]:
import pandas as pd
import numpy as np

import panel as pn
import bdikit as bdi
from bdiviz import BDISchemaMatchingHeatMap

### Loading the data

In [2]:
source = pd.read_csv("datasets/dou.csv")
target = "gdc"

source

,Country,Histologic_Grade_FIGO,Histologic_type,Path_Stage_Primary_Tumor-pT,Path_Stage_Reg_Lymph_Nodes-pN,Clin_Stage_Dist_Mets-cM,Path_Stage_Dist_Mets-pM,tumor_Stage-Pathological,FIGO_stage,BMI,Age,Race,Ethnicity,Gender,Tumor_Site,Tumor_Focality,Tumor_Size_cm
0,United States,FIGO grade 1,Endometrioid,pT1a (FIGO IA),pN0,cM0,Staging Incomplete,Stage I,IA,38.88,64.0,White,Not-Hispanic or Latino,Female,Anterior endometrium,Unifocal,2.9
1,United States,FIGO grade 1,Endometrioid,pT1a (FIGO IA),pNX,cM0,Staging Incomplete,Stage IV,IA,39.76,58.0,White,Not-Hispanic or Latino,Female,Posterior endometrium,Unifocal,3.5
2,United States,FIGO grade 2,Endometrioid,pT1a (FIGO IA),pN0,cM0,Staging Incomplete,Stage I,IA,51.19,50.0,White,Not-Hispanic or Latino,Female,"Other, specify",Unifocal,4.5
3,NaN,NaN,Carcinosarcoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,FIGO grade 2,Endometrioid,pT1a (FIGO IA),pNX,cM0,No pathologic evidence of distant metastasis,Stage I,IA,32.69,75.0,White,Not-Hispanic or Latino,Female,"Other, specify",Unifocal,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Ukraine,FIGO grade 3,Endometrioid,pT1a (FIGO IA),pNX,cM0,Staging Incomplete,Stage I,IA,29.40,75.0,NaN,NaN,Female,"Other, specify",Unifocal,4.2
100,Ukraine,FIGO grade 2,Endometrioid,pT2 (FIGO II),pN0,cM0,Staging Incomplete,Stage II,II,35.42,74.0,NaN,NaN,Female,"Other, specify",Unifocal,1.5
101,United States,NaN,Serous,pT2 (FIGO II),pN0,Staging Incomplete,Staging Incomplete,Stage II,II,24.32,85.0,Black or African American,Not-Hispanic or Latino,Female,"Other, specify",Unifocal,3.8
102,Ukraine,NaN,Serous,pT1a (FIGO IA),pN0,cM0,Staging Incomplete,Stage I,IA,34.06,70.0,NaN,NaN,Female,"Other, specify",Unifocal,5.0
103,Ukraine,NaN,Serous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Visualize Top Candidates in BDI-Viz Heatmap


#### Spotlighted Features

- **Interactive Heatmap**: Click on a heatmap cell to select candidates.
- **Candidate Manipulation**:
  - Use the **Accept Match**, **Reject Match**, and **Discard Column** buttons to manage matching candidates.
  - Undo or redo actions with the **Undo** and **Redo** buttons.
- **Value Comparisons**: Explore similar candidate values in detail.
- **Detailed Analysis**: Examine value distributions and schema descriptions for selected attributes.
- **Filtering Options**:
  - Filter by candidate data type using the **Candidate Type Selector**.
  - Identify similar source columns with the **Similar Sources Slider** (based on embeddings).
  - Adjust threshold values with the **Candidate Threshold Slider** to refine matches.


**Note:** This result is generated by a finetuned language model, BDI-Viz can also be used with other matching methods as long as we have the top-k candidates.

In [3]:
heatmap_manager = BDISchemaMatchingHeatMap(
    source,
    target=target,
    top_k=40,
    ai_assitant=False,
)

heatmap_manager.plot_heatmap()

Column(scroll=True)
    [0] Row(styles={'background': '...}, width=1200)
        [0] Select(name='Source Column', options=['Country', 'Histologic_Gr...], value='Country', width=120)
        [1] Select(name='Candidate Type', options=['All', 'enum', ...], value='All', width=120)
        [2] IntSlider(end=5, name='Similar Sources', width=150)
        [3] FloatSlider(name='Candidate Threshold', step=0.01, value=0.1, width=150)
        [4] Column
            [0] Button(button_type='success', name='Accept Match')
            [1] Button(button_type='danger', name='Reject Match')
            [2] Button(button_type='warning', name='Discard Column')
        [5] Column
            [0] Button(button_style='outline', button_type='warning', name='Undo')
            [1] Button(button_style='outline', button_type='primary', name='Redo')
        [6] Column
            [0] Button(button_type='primary', name='Show/Hide AI Assistant')
            [1] Button(button_type='primary', name='Show/Hide Operation Log')
    [1] ParamFunction(function, _pane=Str, defer_load=False)
    [2] Spacer(height=5)
    [3] Column
        [0] ParamFunction(function, _pane=Column, defer_load=False)


### Pass Results to BDI-Kit

BDI-Viz seamlessly integrates as an extension of BDI-Kit. By passing results from BDI-Viz to BDI-Kit, you can retain and utilize all manually updated candidates for further processing.

In [4]:
from bdikit.mapping_algorithms.column_mapping.algorithms import TwoPhaseSchemaMatcher

two_phase_viz = TwoPhaseSchemaMatcher(top_k_matcher=heatmap_manager)
column_mappings = bdi.match_schema(source, target=target, method=two_phase_viz)
column_mappings

                           source             target
0                         Country   country_of_birth
1           Histologic_Grade_FIGO        tumor_grade
2                 Histologic_type  primary_diagnosis
3     Path_Stage_Primary_Tumor-pT
4   Path_Stage_Reg_Lymph_Nodes-pN  ajcc_pathologic_n
5         Clin_Stage_Dist_Mets-cM    ajcc_clinical_m
6         Path_Stage_Dist_Mets-pM
7        tumor_Stage-Pathological
8                      FIGO_stage         figo_stage
9                             BMI                bmi
10                            Age   age_at_diagnosis
11                           Race               race
12                      Ethnicity          ethnicity
13                         Gender             gender
14                     Tumor_Site        tumor_shape
15                 Tumor_Focality     tumor_focality
16                  Tumor_Size_cm        tumor_depth

In [5]:
column_mappings = column_mappings[column_mappings["target"].str.strip().astype(bool)]
mappings = bdi.match_values(
    source,
    column_mapping=column_mappings,
    target=target,
    method="tfidf",
)

for mapping in mappings:
    print(f"{mapping.attrs['source']} => {mapping.attrs['target']}")
    display(mapping)
    print("")

Country => country_of_birth

          source         target  similarity
0  United States  United States         1.0
1        Ukraine        Ukraine         1.0
2         Poland         Poland         1.0
3            NaN            NaN         NaN
4  Other_specify            NaN         NaN

Histologic_Grade_FIGO => tumor_grade

         source     target  similarity
0  FIGO grade 1  Low Grade       0.482
1  FIGO grade 2  Low Grade       0.482
2  FIGO grade 3  Low Grade       0.482
3           NaN    Unknown       0.303

Histologic_type => primary_diagnosis

           source                     target  similarity
0  Carcinosarcoma        Carcinosarcoma, NOS       0.969
1    Endometrioid  Endometrioid adenoma, NOS       0.897
2      Clear cell         Clear cell adenoma       0.853
3          Serous      Serous carcinoma, NOS       0.755

Path_Stage_Primary_Tumor-pT => ajcc_pathologic_t

             source   target  similarity
0    pT1b (FIGO IB)      T1b       0.535
1    pT1a (FIGO IA)      T1a       0.507
2  pT3b (FIGO IIIB)      T3b       0.437
3  pT3a (FIGO IIIA)      T3a       0.416
4               NaN  Unknown       0.348
5     pT2 (FIGO II)      NaN         NaN
6      pT1 (FIGO I)      NaN         NaN

Path_Stage_Reg_Lymph_Nodes-pN => ajcc_pathologic_n

             source  target  similarity
0               pNX      NX       0.666
1               pN0      N0       0.564
2  pN1 (FIGO IIIC1)  N1bIII       0.526
3  pN2 (FIGO IIIC2)  N1bIII       0.455
4               NaN     NaN         NaN

Clin_Stage_Dist_Mets-cM => ajcc_clinical_m

               source    target  similarity
0                 cM0  cM0 (i+)       0.896
1                 cM1        M1       0.583
2                 NaN       NaN         NaN
3  Staging Incomplete       NaN         NaN

Path_Stage_Dist_Mets-pM => ajcc_pathologic_m

,source,target,similarity
0,pM1,M1,0.511
1,No pathologic evidence of distant metastasis,Not Allowed To Collect,0.332
2,NaN,NaN,NaN
3,Staging Incomplete,NaN,NaN

tumor_Stage-Pathological => ajcc_pathologic_stage

      source     target  similarity
0    Stage I    Stage I       1.000
1   Stage IV   Stage IV       1.000
2  Stage III  Stage III       1.000
3   Stage II   Stage II       1.000
4        NaN    Unknown       0.375

FIGO_stage => figo_stage

  source       target  similarity
0  IIIC2  Stage IIIC2       0.889
1  IIIC1  Stage IIIC1       0.889
2    IVB    Stage IVB       0.854
3   IIIB   Stage IIIB       0.849
4   IIIA   Stage IIIA       0.822
5     II    Stage III       0.687
6     IB     Stage IB       0.649
7     IA     Stage IA       0.586
8    NaN      Unknown       0.350

Race => race

                      source                            target  similarity
0                      White                             white       1.000
1                      Asian                             asian       1.000
2               Not Reported                      not reported       1.000
3  Black or African American         black or african american       1.000
4                        NaN  american indian or alaska native       0.359

Ethnicity => ethnicity

                   source                  target  similarity
0      Hispanic or Latino      hispanic or latino       1.000
1  Not-Hispanic or Latino  not hispanic or latino       0.935
2                     NaN                     NaN         NaN
3            Not reported                     NaN         NaN

Gender => gender

   source  target  similarity
0  Female  female         1.0
1     NaN     NaN         NaN

Tumor_Focality => tumor_focality

       source      target  similarity
0    Unifocal    Unifocal         1.0
1  Multifocal  Multifocal         1.0
2         NaN         NaN         NaN